// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8mmT4Je-XaML1LMGBYy2TmOrfzNocj7k',
    appId: '1:199659708643:web:7b104d7da7374fe65ca5d6',
    messagingSenderId: '199659708643',
    projectId: 'student-app-info',
    authDomain: 'student-app-info.firebaseapp.com',
    storageBucket: 'student-app-info.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_TjuGaz83cr_p2cNl4Ggg0LPxbhWLHt4',
    appId: '1:199659708643:android:3f57faa24ae306c75ca5d6',
    messagingSenderId: '199659708643',
    projectId: 'student-app-info',
    storageBucket: 'student-app-info.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQWFoMyx-zZbJlNbPTZfCqJgx5NBh0BdE',
    appId: '1:199659708643:ios:1a60a0fb70e719875ca5d6',
    messagingSenderId: '199659708643',
    projectId: 'student-app-info',
    storageBucket: 'student-app-info.appspot.com',
    iosBundleId: 'com.example.firebaseCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQWFoMyx-zZbJlNbPTZfCqJgx5NBh0BdE',
    appId: '1:199659708643:ios:38d77258849005705ca5d6',
    messagingSenderId: '199659708643',
    projectId: 'student-app-info',
    storageBucket: 'student-app-info.appspot.com',
    iosBundleId: 'com.example.firebaseCrudApp.RunnerTests',
  );
}
